[package]
name = "arrow-benches"
description = "Apache Arrow micro benchmarks"
version = "4.0.0-SNAPSHOT"
edition = "2018"
authors = ["Apache Arrow <dev@arrow.apache.org>"]
homepage = "https://github.com/apache/arrow"
repository = "https://github.com/apache/arrow"
license = "Apache-2.0"

[dependencies]
arrow = { path = "../arrow", version = "4.0.0-SNAPSHOT"}

[dev-dependencies]
criterion = "0.3"
rand = "0.7"
chrono = "0.4"

[[bench]]
name = "aggregate_kernels"
harness = false

[[bench]]
name = "array_from_vec"
harness = false

[[bench]]
name = "builder"
harness = false

[[bench]]
name = "buffer_bit_ops"
harness = false

[[bench]]
name = "boolean_kernels"
harness = false

[[bench]]
name = "arithmetic_kernels"
harness = false

[[bench]]
name = "cast_kernels"
harness = false

[[bench]]
name = "comparison_kernels"
harness = false

[[bench]]
name = "filter_kernels"
harness = false

[[bench]]
name = "take_kernels"
harness = false

[[bench]]
name = "length_kernel"
harness = false

[[bench]]
name = "sort_kernel"
harness = false

[[bench]]
name = "csv_writer"
harness = false

[[bench]]
name = "json_reader"
harness = false

[[bench]]
name = "equal"
harness = false

[[bench]]
name = "array_slice"
harness = false

[[bench]]
name = "concatenate_kernel"
harness = false

[[bench]]
name = "mutable_array"
harness = false

[[bench]]
name = "buffer_create"
harness = false